apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: prefect-postgresql-initdb
    files:
      - initdb.sql
resources:
  - sts.yaml
  - svc-headless.yaml
  - svc.yaml
