apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/version: "2021.05.25"
  app.kubernetes.io/instance: prefect-server
resources:
  - sa.yaml
  - apollo
  - graphql
  - hasura
  - towel
  - ui
