apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: prefect-server
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kustomize:
        paths:
          - manifests/overlays/dev
