apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prefect-agent
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prefect-agent
  targetCPUUtilizationPercentage: 80
