apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-agent-role
  labels:
    app.kubernetes.io/name: prefect
    app.kubernetes.io/component: agent-role
rules:
  - apiGroups:
      - batch
      - extensions
    resources:
      - jobs
      - jobs/status
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - pods/log
      - services
    verbs:
      - "*"
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-agent-role-binding
  labels:
    app.kubernetes.io/name: prefect
    app.kubernetes.io/component: agent-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefect-agent-role
subjects:
  - kind: ServiceAccount
    name: prefect
