apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-ui
  labels:
    app.kubernetes.io/name: prefect-server
    app.kubernetes.io/component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prefect-server
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prefect-server
        app.kubernetes.io/component: ui
    spec:
      serviceAccountName: prefect-server
      containers:
        - name: ui
          image: prefecthq/ui:2021-05-25
          command:
            - /intercept.sh
          env:
            - name: PREFECT_SERVER__APOLLO_URL
              value: http://localhost:4200/graphql
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 1Gi
