apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: prefect-system
configMapGenerator:
  - name: prefect-cloud-sql
    literals:
      - connection-name=prefect
resources:
  - cnrm.yaml
  - deploy.yaml
