apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
  - name: prefect-postgresql-initdb
    files:
      - initdb.sql
resources:
  - sts.yaml
  - svc-headless.yaml
  - svc.yaml
  - pvc.yaml
