apiVersion: v1
kind: Service
metadata:
  name: prefect-postgresql-headless
  labels:
    app.kubernetes.io/name: prefect
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app.kubernetes.io/name: prefect
    app.kubernetes.io/component: postgresql
